#include "protocalfams.h"


int ProtocalFams::values[protocols_count] = {
    PF_UNSPEC	,
    PF_LOCAL	,
    PF_UNIX		,
    PF_FILE		,
    PF_INET		,
    PF_AX25		,
    PF_IPX		,
    PF_APPLETALK	,
    PF_NETROM	,
    PF_BRIDGE	,
    PF_ATMPVC	,
    PF_X25		,
    PF_INET6	,
    PF_ROSE		,
    PF_DECnet	,
    PF_NETBEUI	,
    PF_SECURITY	,
    PF_KEY		,
    PF_NETLINK	,
    PF_ROUTE	,
    PF_PACKET	,
    PF_ASH		,
    PF_ECONET	,
    PF_ATMSVC	,
    PF_RDS		,
    PF_SNA		,
    PF_IRDA		,
    PF_PPPOX	,
    PF_WANPIPE	,
    PF_LLC		,
    PF_IB		,
    PF_MPLS		,
    PF_CAN		,
    PF_TIPC		,
    PF_BLUETOOTH	,
    PF_IUCV		,
    PF_RXRPC	,
    PF_ISDN		,
    PF_PHONET	,
    PF_IEEE802154	,
    PF_CAIF		,
    PF_ALG		,
    PF_NFC		,
    PF_VSOCK	,
    PF_KCM		,
    PF_QIPCRTR	,
    PF_SMC		,
    PF_MAX
};

// grep -o '#define PF_[A-Z0-9a-z]\+[[:blank:]]\+' /usr/include/bits/socket.h | sed 's~#define ~~g' | sed 's/[[:blank:]]\+//' | sed 's/.*/"&",/'
const char* ProtocalFams::names[protocols_count] = {
    "PF_UNSPEC",
    "PF_LOCAL",
    "PF_UNIX",
    "PF_FILE",
    "PF_INET",
    "PF_AX25",
    "PF_IPX",
    "PF_APPLETALK",
    "PF_NETROM",
    "PF_BRIDGE",
    "PF_ATMPVC",
    "PF_X25",
    "PF_INET6",
    "PF_ROSE",
    "PF_DECnet",
    "PF_NETBEUI",
    "PF_SECURITY",
    "PF_KEY",
    "PF_NETLINK",
    "PF_ROUTE",
    "PF_PACKET",
    "PF_ASH",
    "PF_ECONET",
    "PF_ATMSVC",
    "PF_RDS",
    "PF_SNA",
    "PF_IRDA",
    "PF_PPPOX",
    "PF_WANPIPE",
    "PF_LLC",
    "PF_IB",
    "PF_MPLS",
    "PF_CAN",
    "PF_TIPC",
    "PF_BLUETOOTH",
    "PF_IUCV",
    "PF_RXRPC",
    "PF_ISDN",
    "PF_PHONET",
    "PF_IEEE802154",
    "PF_CAIF",
    "PF_ALG",
    "PF_NFC",
    "PF_VSOCK",
    "PF_KCM",
    "PF_QIPCRTR",
    "PF_SMC",
    "PF_MAX"
};
